//! Quotient geometry: [`QuotientSpace`] and [`FlatTorus3`].
//!
//! A quotient Space is a [`Space`] whose points are orbits of a discrete
//! subgroup Γ of its isometry group acting freely and properly discontinuously
//! (the deck group). Loam represents an orbit by a lift: a point of the
//! universal cover. Every metric primitive is Γ-invariant, so any lift answers
//! for the orbit, and [`QuotientSpace::wrap_to_domain`] names the canonical one.
//!
//! Two contracts split apart here and must not be conflated:
//!
//! - [`Space::exp`] and [`Space::log`] are quotient operations. They accept any
//!   lift and `exp` returns the canonical representative, which is what makes a
//!   ray march continue across the gluing without the caller knowing a gluing
//!   exists.
//! - [`IsometryGroup::iso_apply`] is a *covering-space* operation and
//!   deliberately does not re-canonicalize. Canonicalizing would collapse Γ to
//!   the identity and destroy [`QuotientSpace::wrap_to_domain`]'s
//!   postcondition, which is the one statement that lets a caller ask which
//!   deck element a crossing used.
//!
//! Consequence for SDF emission: a primitive whose formula is raw chart
//! arithmetic (`dot(p, n) - d`, `abs(p) - b`) is not Γ-periodic and is therefore
//! wrong across the gluing. Only primitives routed through [`Space::distance`]
//! (spheres) transfer to a quotient unchanged, which is why [`FlatTorus3`]
//! reports [`Space::is_chart_flat`] false despite being flat as a Riemannian
//! manifold.

use std::borrow::Cow;

use glam::{BVec3, Vec3};

use crate::euclidean::Iso3;
use crate::space::{IsometryGroup, Space, WgslSpace};

/// A [`Space`] presented as a quotient of its universal cover by a discrete
/// group of isometries, with a fundamental domain the caller can fold into.
///
/// The associated [`IsometryGroup::Iso`] is an isometry of the *cover*; deck
/// elements are the subset of them generated by [`QuotientSpace::face_pairings`].
pub trait QuotientSpace: IsometryGroup {
    /// Face-pairing generators of the deck group, in a fixed order.
    ///
    /// One generator per identified face pair: it carries the fundamental
    /// domain across one face, and its [`IsometryGroup::iso_inverse`] carries it
    /// across the opposite one. Order is part of the contract because products
    /// of generators must be reproducible across runs.
    fn face_pairings(&self) -> impl Iterator<Item = Self::Iso>;

    /// Whether `p` is the canonical lift of its orbit.
    ///
    /// Exactly the fixpoints of [`QuotientSpace::wrap_to_domain`]: the domain is
    /// half-open, so each orbit has exactly one member satisfying this.
    fn in_fundamental_domain(&self, p: Self::Point) -> bool;

    /// The canonical lift `q` of `p`'s orbit, with the deck element `g` that
    /// produced it: `iso_apply(g, p) == q`, and `g` is the identity exactly when
    /// `p` was already canonical.
    fn wrap_to_domain(&self, p: Self::Point) -> (Self::Point, Self::Iso);
}

/// The flat 3-torus E³/Λ for a rectangular lattice Λ = c₀Z × c₁Z × c₂Z.
///
/// The fundamental domain is the half-open box `[-cᵢ/2, cᵢ/2)`, so the deck
/// group is Z³ acting by translations and the six faces are glued in opposite
/// pairs. Curvature is zero everywhere; all the non-Euclidean behavior lives in
/// the fundamental group.
///
/// Rectangular rather than an arbitrary basis on purpose: for an orthogonal
/// lattice the closest-vector problem separates per axis, so the reduction to
/// the fundamental domain is three independent roundings and is *exact*
/// (Conway & Sloane 1988, *Sphere Packings, Lattices and Groups*, ch. 4 §1, the
/// Zⁿ decoding algorithm). An oblique basis needs a search: Babai rounding is
/// not exact CVP on a skewed basis, and a wrong nearest lattice point is a
/// silently wrong metric, not a slow one.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FlatTorus3 {
    cell: Vec3,
}

impl FlatTorus3 {
    /// `cell` holds the three side lengths of the fundamental box; each must be
    /// finite and strictly positive.
    pub fn new(cell: Vec3) -> Self {
        assert!(
            cell.is_finite() && cell.cmpgt(Vec3::ZERO).all(),
            "FlatTorus3 cell must be finite and positive, got {cell:?}"
        );
        Self { cell }
    }

    /// Cubic cell of the given side length.
    pub fn cube(side: f32) -> Self {
        Self::new(Vec3::splat(side))
    }

    pub fn cell(&self) -> Vec3 {
        self.cell
    }

    /// Largest radius within which [`Space::exp`] is injective and
    /// `log(from, exp(from, v)) == v`. Half the shortest lattice vector.
    pub fn injectivity_radius(&self) -> f32 {
        0.5 * self.cell.min_element()
    }

    /// Integer lattice coordinates of the cell containing `p`, as an
    /// integral-valued `Vec3`.
    ///
    /// `floor(p/c + 1/2)` alone is not enough: when `pᵢ` sits an ulp inside the
    /// upper face, `pᵢ/cᵢ` can round up onto the tie and send the index one cell
    /// too far, putting the representative outside the domain. The correction
    /// tests the residual that was actually computed rather than the exact
    /// quotient, so it closes the case the rounding created; the residual is
    /// never more than one cell out, so one step suffices.
    fn lattice_index(&self, p: Vec3) -> Vec3 {
        let index = (p / self.cell + Vec3::splat(0.5)).floor();
        let residual = p - self.cell * index;
        let half = 0.5 * self.cell;
        index - unit_where(residual.cmplt(-half)) + unit_where(residual.cmpge(half))
    }

    /// The canonical lift of `p`'s orbit.
    fn wrap(&self, p: Vec3) -> Vec3 {
        p - self.cell * self.lattice_index(p)
    }
}

fn unit_where(mask: BVec3) -> Vec3 {
    Vec3::select(mask, Vec3::ONE, Vec3::ZERO)
}

impl Space for FlatTorus3 {
    type Point = Vec3;
    type Vector = Vec3;

    /// Geodesic distance in the quotient: the length of the shortest lift of
    /// `a - b`, i.e. `min over λ in Λ of |a - b - λ|`.
    fn distance(&self, a: Vec3, b: Vec3) -> f32 {
        self.wrap(a - b).length()
    }

    /// Travel from `at` along the geodesic and return the *canonical* lift of
    /// the endpoint. Canonicalizing here is what makes stepped ray continuation
    /// and a single long geodesic agree without a portal test at the caller.
    fn exp(&self, at: Vec3, v: Vec3) -> Vec3 {
        self.wrap(at + v)
    }

    /// The shortest tangent vector reaching `to`'s orbit from `from`.
    ///
    /// Multivalued on the quotient; this branch takes the minimal
    /// representative. It is discontinuous across the cut locus (the faces of
    /// the domain centered on `from`), and `exp(from, log(from, to)) == to` only
    /// for `to` within [`FlatTorus3::injectivity_radius`] of `from`.
    fn log(&self, from: Vec3, to: Vec3) -> Vec3 {
        self.wrap(to - from)
    }

    fn parallel_transport(&self, _from: Vec3, _to: Vec3, v: Vec3) -> Vec3 {
        // Zero curvature: transport is the identity along every path, so the
        // holonomy of the quotient is trivial despite its nontrivial pi_1.
        v
    }

    /// False despite zero curvature. `is_chart_flat` licenses raw chart
    /// arithmetic as the geometry, and chart arithmetic is not Λ-periodic:
    /// `dot(p, n) - d` disagrees with the quotient across the gluing.
    fn is_chart_flat(&self) -> bool {
        false
    }
}

impl IsometryGroup for FlatTorus3 {
    type Iso = Iso3;

    fn iso_identity(&self) -> Iso3 {
        Iso3::IDENTITY
    }

    fn iso_compose(&self, a: Iso3, b: Iso3) -> Iso3 {
        Iso3 {
            rotation: a.rotation * b.rotation,
            translation: a.rotation * b.translation + a.translation,
        }
    }

    fn iso_inverse(&self, a: Iso3) -> Iso3 {
        let inverse_rotation = a.rotation.inverse();
        Iso3 {
            rotation: inverse_rotation,
            translation: inverse_rotation * (-a.translation),
        }
    }

    /// Acts on lifts, in the cover. No canonicalization: see the module doc.
    fn iso_apply(&self, iso: Iso3, p: Vec3) -> Vec3 {
        iso.rotation * p + iso.translation
    }

    fn iso_transport(&self, iso: Iso3, _at: Vec3, v: Vec3) -> Vec3 {
        iso.rotation * v
    }
}

impl QuotientSpace for FlatTorus3 {
    fn face_pairings(&self) -> impl Iterator<Item = Iso3> {
        [
            Iso3::from_translation(Vec3::new(self.cell.x, 0.0, 0.0)),
            Iso3::from_translation(Vec3::new(0.0, self.cell.y, 0.0)),
            Iso3::from_translation(Vec3::new(0.0, 0.0, self.cell.z)),
        ]
        .into_iter()
    }

    fn in_fundamental_domain(&self, p: Vec3) -> bool {
        let half = 0.5 * self.cell;
        p.cmpge(-half).all() && p.cmplt(half).all()
    }

    fn wrap_to_domain(&self, p: Vec3) -> (Vec3, Iso3) {
        let translation = -(self.cell * self.lattice_index(p));
        // `iso_apply` adds this translation to `p`, reproducing `wrap`'s
        // subtraction bit for bit; the postcondition is an identity, not an
        // approximation.
        (p + translation, Iso3::from_translation(translation))
    }
}

impl WgslSpace for FlatTorus3 {
    fn wgsl_impl(&self) -> Cow<'static, str> {
        Cow::Owned(flat_torus3_wgsl(self.cell))
    }
}

/// Prelude mirroring [`FlatTorus3`]'s Rust arithmetic expression for
/// expression, including the lattice-index correction.
///
/// Parity is to one ulp of the cell scale, not bitwise: a shader compiler may
/// contract the multiply-add that forms the residual. Off the faces that is an
/// ulp; on a face it decides which of two representatives comes back, so the
/// GPU can return the lift one cell over. Both name the same point of the
/// quotient, which is the only claim callers may rely on across the boundary.
///
/// `{:?}` on `f32` prints the shortest literal that round-trips and always
/// carries a decimal point or exponent, so the baked cell parses back to the
/// exact input bits.
fn flat_torus3_wgsl(cell: Vec3) -> String {
    let (cx, cy, cz) = (cell.x, cell.y, cell.z);
    let (hx, hy, hz) = (0.5 * cell.x, 0.5 * cell.y, 0.5 * cell.z);
    format!(
        r#"
// loam-math :: FlatTorus3 (v0 Space WGSL ABI)
// Unbounded arc: the quotient is compact, so the march kernel's boundary
// escape must never fire.
const LOAM_MAX_ARC: f32 = 1e9;
const LOAM_TORUS_CELL: vec3<f32> = vec3<f32>({cx:?}, {cy:?}, {cz:?});
const LOAM_TORUS_HALF: vec3<f32> = vec3<f32>({hx:?}, {hy:?}, {hz:?});

fn loam_torus_index(p: vec3<f32>) -> vec3<f32> {{
    let index = floor(p / LOAM_TORUS_CELL + vec3<f32>(0.5));
    let residual = p - LOAM_TORUS_CELL * index;
    let below = select(vec3<f32>(0.0), vec3<f32>(1.0), residual < -LOAM_TORUS_HALF);
    let above = select(vec3<f32>(0.0), vec3<f32>(1.0), residual >= LOAM_TORUS_HALF);
    return index - below + above;
}}

fn loam_torus_wrap(p: vec3<f32>) -> vec3<f32> {{
    return p - LOAM_TORUS_CELL * loam_torus_index(p);
}}

fn loam_distance(a: vec3<f32>, b: vec3<f32>) -> f32 {{ return length(loam_torus_wrap(a - b)); }}
fn loam_origin_distance(p: vec3<f32>) -> f32 {{ return length(loam_torus_wrap(p)); }}
fn loam_exp(at: vec3<f32>, v: vec3<f32>) -> vec3<f32> {{ return loam_torus_wrap(at + v); }}
fn loam_log(p_from: vec3<f32>, p_to: vec3<f32>) -> vec3<f32> {{ return loam_torus_wrap(p_to - p_from); }}
fn loam_parallel_transport(p_from: vec3<f32>, p_to: vec3<f32>, v: vec3<f32>) -> vec3<f32> {{ return v; }}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;

    const CELL: Vec3 = Vec3::new(2.0, 3.0, 1.5);

    fn torus() -> FlatTorus3 {
        FlatTorus3::new(CELL)
    }

    /// xorshift32; the sweeps below need a few 10⁵ deterministic samples and a
    /// seeded generator is the only kind allowed in this crate's tests.
    struct Xorshift(u32);

    impl Xorshift {
        fn next_u32(&mut self) -> u32 {
            self.0 ^= self.0 << 13;
            self.0 ^= self.0 >> 17;
            self.0 ^= self.0 << 5;
            self.0
        }

        /// Uniform in `[-span, span)`.
        fn signed(&mut self, span: f32) -> f32 {
            let unit = self.next_u32() as f32 / u32::MAX as f32;
            (unit * 2.0 - 1.0) * span
        }

        fn point(&mut self, span: f32) -> Vec3 {
            Vec3::new(self.signed(span), self.signed(span), self.signed(span))
        }
    }

    /// Lifts chosen to stress the rounding the lattice-index correction exists
    /// for: exact face coordinates, an ulp either side of them, and exact
    /// lattice translates of all three.
    fn boundary_lifts(cell: Vec3) -> Vec<Vec3> {
        let half = 0.5 * cell;
        let mut lifts = Vec::new();
        for axis in 0..3 {
            for sign in [-1.0_f32, 1.0] {
                let edge = sign * half[axis];
                for coordinate in [
                    edge,
                    f32::from_bits(edge.to_bits() - 1),
                    f32::from_bits(edge.to_bits() + 1),
                ] {
                    for copy in -3..=3 {
                        let mut p = Vec3::new(0.25, -0.5, 0.125);
                        p[axis] = coordinate + copy as f32 * cell[axis];
                        lifts.push(p);
                    }
                }
            }
        }
        lifts
    }

    // ---- fundamental domain ------------------------------------------------

    /// The postcondition every other quotient claim rests on. A representative
    /// an ulp outside the box is a portal that occasionally fails to close, so
    /// the sweep includes the boundary lifts explicitly rather than trusting
    /// uniform sampling to find them.
    #[test]
    fn wrap_lands_every_lift_in_the_half_open_fundamental_domain() {
        let t = torus();
        let mut rng = Xorshift(0x5eed_1234);
        let mut lifts = boundary_lifts(CELL);
        for _ in 0..200_000 {
            lifts.push(rng.point(40.0));
        }
        for p in lifts {
            let (q, _) = t.wrap_to_domain(p);
            assert!(
                t.in_fundamental_domain(q),
                "wrap({p:?}) = {q:?} escaped the domain of cell {CELL:?}"
            );
        }
    }

    /// `in_fundamental_domain` and `wrap_to_domain` must name the same set, or
    /// membership is a second opinion instead of a predicate.
    #[test]
    fn fundamental_domain_membership_is_exactly_the_wrap_fixpoint() {
        let t = torus();
        let mut rng = Xorshift(0x1337_beef);
        for _ in 0..50_000 {
            let p = rng.point(6.0);
            let (q, _) = t.wrap_to_domain(p);
            assert_eq!(t.in_fundamental_domain(p), p == q, "at {p:?}");
        }
    }

    /// The deck element is not advisory: applying it to the lift reproduces the
    /// representative exactly, which is what lets a caller carry state (a
    /// velocity, a portal count, a colour) across the gluing.
    #[test]
    fn the_returned_deck_element_reproduces_the_representative_exactly() {
        let t = torus();
        let mut rng = Xorshift(0x0bad_f00d);
        let mut lifts = boundary_lifts(CELL);
        for _ in 0..50_000 {
            lifts.push(rng.point(25.0));
        }
        for p in lifts {
            let (q, g) = t.wrap_to_domain(p);
            assert_eq!(t.iso_apply(g, p), q, "deck element disagreed at {p:?}");
        }
    }

    #[test]
    fn wrapping_an_interior_point_returns_the_identity_deck_element() {
        let t = torus();
        let p = Vec3::new(0.3, -1.1, 0.4);
        let (q, g) = t.wrap_to_domain(p);
        assert_eq!(q, p);
        assert_eq!(g, Iso3::IDENTITY);
    }

    // ---- the deck group ----------------------------------------------------

    /// The generators are the three positive lattice translations; the opposite
    /// face is paired by the inverse. A sign flip here glues the room to itself
    /// with a shear and nothing downstream would notice.
    #[test]
    fn face_pairings_are_the_three_positive_lattice_translations() {
        let t = torus();
        let pairings: Vec<Iso3> = t.face_pairings().collect();
        assert_eq!(pairings.len(), 3);
        for (axis, pairing) in pairings.iter().enumerate() {
            let mut expected = Vec3::ZERO;
            expected[axis] = CELL[axis];
            assert_eq!(pairing.translation, expected);
            assert_eq!(pairing.rotation, glam::Quat::IDENTITY);
            assert_eq!(t.iso_inverse(*pairing).translation, -expected);
        }
    }

    /// Deck elements act: composition of isometries agrees with composition of
    /// their actions, the identity acts trivially, and every element is
    /// invertible. Products are taken over words in the generators so the test
    /// covers the group, not just the generating set.
    #[test]
    fn deck_group_composition_is_a_group_action_on_lifts() {
        let t = torus();
        let generators: Vec<Iso3> = t
            .face_pairings()
            .flat_map(|g| [g, t.iso_inverse(g)])
            .collect();
        let mut rng = Xorshift(0xfeed_face);

        for _ in 0..20_000 {
            let a = word(&t, &generators, &mut rng);
            let b = word(&t, &generators, &mut rng);
            let p = rng.point(8.0);

            let sequential = t.iso_apply(a, t.iso_apply(b, p));
            let composed = t.iso_apply(t.iso_compose(a, b), p);
            assert_relative_eq!(sequential.x, composed.x, epsilon = 1e-5);
            assert_relative_eq!(sequential.y, composed.y, epsilon = 1e-5);
            assert_relative_eq!(sequential.z, composed.z, epsilon = 1e-5);

            assert_eq!(t.iso_apply(t.iso_identity(), p), p);

            let round_trip = t.iso_apply(t.iso_inverse(a), t.iso_apply(a, p));
            assert_relative_eq!(round_trip.x, p.x, epsilon = 1e-5);
            assert_relative_eq!(round_trip.y, p.y, epsilon = 1e-5);
            assert_relative_eq!(round_trip.z, p.z, epsilon = 1e-5);
        }
    }

    fn word(t: &FlatTorus3, generators: &[Iso3], rng: &mut Xorshift) -> Iso3 {
        let length = (rng.next_u32() % 5) as usize;
        (0..length).fold(t.iso_identity(), |accumulated, _| {
            let pick = generators[(rng.next_u32() as usize) % generators.len()];
            t.iso_compose(accumulated, pick)
        })
    }

    /// The whole point of a quotient: the deck group is invisible to the
    /// canonical representative.
    #[test]
    fn wrap_is_invariant_under_the_deck_group() {
        let t = torus();
        let generators: Vec<Iso3> = t
            .face_pairings()
            .flat_map(|g| [g, t.iso_inverse(g)])
            .collect();
        let mut rng = Xorshift(0x00c0_ffee);
        for _ in 0..20_000 {
            let p = rng.point(5.0);
            let (q, _) = t.wrap_to_domain(p);
            let g = word(&t, &generators, &mut rng);
            let (q_translated, _) = t.wrap_to_domain(t.iso_apply(g, p));
            assert_relative_eq!(q_translated.x, q.x, epsilon = 1e-4);
            assert_relative_eq!(q_translated.y, q.y, epsilon = 1e-4);
            assert_relative_eq!(q_translated.z, q.z, epsilon = 1e-4);
        }
    }

    // ---- the quotient metric -----------------------------------------------

    /// `distance` must be the true minimum over Λ, not the chart distance of
    /// two representatives. Brute force searches a 7³ block of translates
    /// *centered on the separation*, three cells past the one the closed form
    /// could be wrong by on each axis.
    #[test]
    fn distance_is_the_minimum_over_the_lattice() {
        let t = torus();
        let mut rng = Xorshift(0xdead_10cc);
        for _ in 0..20_000 {
            let a = rng.point(4.0);
            let b = rng.point(4.0);
            let center = ((a - b) / CELL).round();
            let mut brute = f32::INFINITY;
            for i in -3..=3 {
                for j in -3..=3 {
                    for k in -3..=3 {
                        let offset = Vec3::new(i as f32, j as f32, k as f32);
                        brute = brute.min((a - b - CELL * (center + offset)).length());
                    }
                }
            }
            assert_relative_eq!(t.distance(a, b), brute, epsilon = 1e-5);
        }
    }

    /// A metric on the quotient cannot see which lift it was handed.
    #[test]
    fn distance_is_lattice_invariant_symmetric_and_zero_on_the_orbit() {
        let t = torus();
        let generators: Vec<Iso3> = t
            .face_pairings()
            .flat_map(|g| [g, t.iso_inverse(g)])
            .collect();
        let mut rng = Xorshift(0x9e37_79b9);
        for _ in 0..20_000 {
            let a = rng.point(4.0);
            let b = rng.point(4.0);
            let g = word(&t, &generators, &mut rng);

            assert_relative_eq!(t.distance(a, b), t.distance(b, a));
            assert_relative_eq!(
                t.distance(t.iso_apply(g, a), b),
                t.distance(a, b),
                epsilon = 1e-4
            );
            assert_relative_eq!(t.distance(a, t.iso_apply(g, a)), 0.0, epsilon = 1e-4);
        }
    }

    /// Diameter bound: no two points of E³/Λ are further apart than the
    /// half-diagonal of the cell. Catches a wrap that silently gives up on an
    /// axis.
    #[test]
    fn distance_never_exceeds_half_the_cell_diagonal() {
        let t = torus();
        let bound = (0.5 * CELL).length();
        let mut rng = Xorshift(0x2545_f491);
        for _ in 0..50_000 {
            let d = t.distance(rng.point(30.0), rng.point(30.0));
            assert!(d <= bound + 1e-5, "{d} exceeded the diameter bound {bound}");
        }
    }

    #[test]
    fn distance_satisfies_the_triangle_inequality() {
        let t = torus();
        let mut rng = Xorshift(0x7f4a_7c15);
        for _ in 0..50_000 {
            let a = rng.point(5.0);
            let b = rng.point(5.0);
            let c = rng.point(5.0);
            assert!(t.distance(a, c) <= t.distance(a, b) + t.distance(b, c) + 1e-4);
        }
    }

    // ---- geodesics and the gluing ------------------------------------------

    /// Walk out through the +x face and you come back through the -x face at
    /// the matching offset, with the other two coordinates untouched.
    #[test]
    fn crossing_a_face_re_enters_through_the_opposite_face() {
        let t = torus();
        let half = 0.5 * CELL;
        let overshoot = 0.01;
        for axis in 0..3 {
            let mut start = Vec3::new(0.4, -0.7, 0.2);
            start[axis] = half[axis] - overshoot;
            let mut step = Vec3::ZERO;
            step[axis] = 2.0 * overshoot;

            let arrived = t.exp(start, step);
            assert!(t.in_fundamental_domain(arrived));
            assert_relative_eq!(arrived[axis], -half[axis] + overshoot, epsilon = 1e-6);
            for other in 0..3 {
                if other != axis {
                    assert_relative_eq!(arrived[other], start[other]);
                }
            }
        }
    }

    /// Criterion the other way round: the crossing's deck element is the face
    /// pairing itself, and it is what maps the naive straight-line endpoint onto
    /// the point `exp` reports.
    #[test]
    fn a_geodesic_crossing_the_gluing_lands_where_the_face_pairing_says() {
        let t = torus();
        let half = 0.5 * CELL;
        let pairings: Vec<Iso3> = t.face_pairings().collect();

        for (axis, pairing) in pairings.iter().enumerate() {
            let mut start = Vec3::new(0.1, 0.9, -0.3);
            start[axis] = half[axis] - 0.05;
            let mut step = Vec3::ZERO;
            step[axis] = 0.2;

            let uncorrected = start + step;
            let (arrived, deck) = t.wrap_to_domain(uncorrected);

            // Exiting through the +axis face applies the inverse pairing.
            let expected = t.iso_inverse(*pairing);
            assert_eq!(deck.translation, expected.translation, "axis {axis}");
            assert_eq!(t.iso_apply(expected, uncorrected), arrived);
            assert_eq!(t.exp(start, step), arrived);
        }
    }

    /// Ray continuation is `exp` applied one march step at a time. If the two
    /// disagree the shader draws a different world than the simulation walks
    /// through; agreement is what lets the geodesic march kernel cross the
    /// gluing with no portal test at all.
    #[test]
    fn stepped_ray_continuation_matches_a_single_geodesic_exp() {
        let t = torus();
        let mut rng = Xorshift(0x4d59_5f21);
        for _ in 0..5_000 {
            let start = t.wrap(rng.point(1.5));
            let velocity = rng.point(4.0);

            let direct = t.exp(start, velocity);

            const STEPS: usize = 64;
            let mut marched = start;
            for _ in 0..STEPS {
                marched = t.exp(marched, velocity / STEPS as f32);
            }

            // 64 wraps each contribute at most a cell-scaled rounding; the
            // bound is the accumulated worst case, not a fudge factor.
            let residual = t.distance(direct, marched);
            assert!(
                residual < 64.0 * f32::EPSILON * CELL.max_element() * 8.0,
                "stepped {marched:?} vs direct {direct:?}, residual {residual}"
            );
        }
    }

    /// `exp` and `log` invert inside the injectivity radius and not outside it;
    /// the failure past the radius is the cut locus, not a bug, so pin both
    /// halves.
    #[test]
    fn exp_and_log_invert_exactly_within_the_injectivity_radius() {
        let t = torus();
        let radius = t.injectivity_radius();
        assert_relative_eq!(radius, 0.75);

        let mut rng = Xorshift(0x6c07_8965);
        for _ in 0..20_000 {
            let from = t.wrap(rng.point(2.0));
            let direction = rng.point(1.0).normalize_or_zero();
            let v = direction * (0.95 * radius);
            let to = t.exp(from, v);
            let recovered = t.log(from, to);
            assert_relative_eq!(recovered.x, v.x, epsilon = 1e-5);
            assert_relative_eq!(recovered.y, v.y, epsilon = 1e-5);
            assert_relative_eq!(recovered.z, v.z, epsilon = 1e-5);
        }

        // Past the radius the short way home is a different vector: two units
        // along y in a cell of three wraps to one unit backwards.
        let short = t.log(Vec3::ZERO, t.exp(Vec3::ZERO, Vec3::new(0.0, 2.0, 0.0)));
        assert_relative_eq!(short.x, 0.0);
        assert_relative_eq!(short.y, -1.0);
        assert_relative_eq!(short.z, 0.0);
    }

    /// `log` is the shortest lift, so its length is the quotient distance for
    /// every pair. Ties the two primitives together instead of letting them
    /// drift apart.
    #[test]
    fn log_length_equals_quotient_distance() {
        let t = torus();
        let mut rng = Xorshift(0x1c69_b3f5);
        for _ in 0..50_000 {
            let a = rng.point(9.0);
            let b = rng.point(9.0);
            assert_relative_eq!(t.log(a, b).length(), t.distance(a, b));
        }
    }

    #[test]
    #[should_panic(expected = "must be finite and positive")]
    fn a_degenerate_cell_is_rejected_at_construction() {
        FlatTorus3::new(Vec3::new(1.0, 0.0, 1.0));
    }

    // ---- WGSL ABI ----------------------------------------------------------

    /// The march kernel calls these by name; a rename here is a black screen,
    /// and a cell baked at reduced precision is a seam that does not close.
    #[test]
    fn wgsl_prelude_exports_the_abi_and_bakes_a_round_tripping_cell() {
        let cell = Vec3::new(2.0, 3.0, 1.5e-7);
        let source = FlatTorus3::new(cell).wgsl_impl().into_owned();
        for symbol in [
            "fn loam_distance(",
            "fn loam_origin_distance(",
            "fn loam_exp(",
            "fn loam_log(",
            "fn loam_parallel_transport(",
            "fn loam_torus_wrap(",
            "const LOAM_MAX_ARC",
        ] {
            assert!(source.contains(symbol), "missing {symbol}");
        }

        let baked = source
            .split("const LOAM_TORUS_CELL: vec3<f32> = vec3<f32>(")
            .nth(1)
            .and_then(|rest| rest.split(')').next())
            .expect("cell is baked");
        let parsed: Vec<f32> = baked
            .split(", ")
            .map(|c| c.parse().expect("cell literal parses as f32"))
            .collect();
        assert_eq!(parsed, vec![cell.x, cell.y, cell.z], "emitted {baked}");
    }
}
