//! Quotient geometry: [`QuotientSpace`], [`FlatTorus3`] and [`LensSpace`].
//!
//! A quotient Space is a [`Space`] whose points are orbits of a discrete
//! subgroup Γ of its isometry group acting freely and properly discontinuously
//! (the deck group). Loam represents an orbit by a lift: a point of the
//! universal cover. Every metric primitive is Γ-invariant, so any lift answers
//! for the orbit, and [`QuotientSpace::wrap_to_domain`] names the canonical one.
//!
//! Two contracts split apart here and must not be conflated:
//!
//! - [`Space::exp`] and [`Space::log`] are quotient operations. They accept any
//!   lift and `exp` returns the canonical representative, which is what makes a
//!   ray march continue across the gluing without the caller knowing a gluing
//!   exists.
//! - [`IsometryGroup::iso_apply`] is a *covering-space* operation and
//!   deliberately does not re-canonicalize. Canonicalizing would collapse Γ to
//!   the identity and destroy [`QuotientSpace::wrap_to_domain`]'s
//!   postcondition, which is the one statement that lets a caller ask which
//!   deck element a crossing used.
//!
//! Consequence for SDF emission: a primitive whose formula is raw chart
//! arithmetic (`dot(p, n) - d`, `abs(p) - b`) is not Γ-periodic and is therefore
//! wrong across the gluing. Only primitives routed through [`Space::distance`]
//! (spheres) transfer to a quotient unchanged, which is why [`FlatTorus3`]
//! reports [`Space::is_chart_flat`] false despite being flat as a Riemannian
//! manifold.

use std::borrow::Cow;
use std::f32::consts::{PI, TAU};

use glam::{BVec3, Mat4, Vec3, Vec4};

use crate::euclidean::Iso3;
use crate::space::{IsometryGroup, Space, WgslSpace};
use crate::spherical::Iso4;
use crate::spherical_embedded::SphericalS3Embedded;

/// A [`Space`] presented as a quotient of its universal cover by a discrete
/// group of isometries, with a fundamental domain the caller can fold into.
///
/// The associated [`IsometryGroup::Iso`] is an isometry of the *cover*; deck
/// elements are the subset of them generated by [`QuotientSpace::face_pairings`].
pub trait QuotientSpace: IsometryGroup {
    /// Face-pairing generators of the deck group, in a fixed order.
    ///
    /// One generator per identified face pair: it carries the fundamental
    /// domain across one face, and its [`IsometryGroup::iso_inverse`] carries it
    /// across the opposite one. Order is part of the contract because products
    /// of generators must be reproducible across runs.
    fn face_pairings(&self) -> impl Iterator<Item = Self::Iso>;

    /// Whether `p` is the canonical lift of its orbit.
    ///
    /// Exactly the fixpoints of [`QuotientSpace::wrap_to_domain`]: the domain is
    /// half-open, so each orbit has exactly one member satisfying this.
    fn in_fundamental_domain(&self, p: Self::Point) -> bool;

    /// The canonical lift `q` of `p`'s orbit, with the deck element `g` that
    /// produced it: `iso_apply(g, p) == q`, and `g` is the identity exactly when
    /// `p` was already canonical.
    fn wrap_to_domain(&self, p: Self::Point) -> (Self::Point, Self::Iso);
}

/// The flat 3-torus E³/Λ for a rectangular lattice Λ = c₀Z × c₁Z × c₂Z.
///
/// The fundamental domain is the half-open box `[-cᵢ/2, cᵢ/2)`, so the deck
/// group is Z³ acting by translations and the six faces are glued in opposite
/// pairs. Curvature is zero everywhere; all the non-Euclidean behavior lives in
/// the fundamental group.
///
/// Rectangular rather than an arbitrary basis on purpose: for an orthogonal
/// lattice the closest-vector problem separates per axis, so the reduction to
/// the fundamental domain is three independent roundings and is *exact*
/// (Conway & Sloane 1988, *Sphere Packings, Lattices and Groups*, ch. 4 §1, the
/// Zⁿ decoding algorithm). An oblique basis needs a search: Babai rounding is
/// not exact CVP on a skewed basis, and a wrong nearest lattice point is a
/// silently wrong metric, not a slow one.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FlatTorus3 {
    cell: Vec3,
}

impl FlatTorus3 {
    /// `cell` holds the three side lengths of the fundamental box; each must be
    /// finite and strictly positive.
    pub fn new(cell: Vec3) -> Self {
        assert!(
            cell.is_finite() && cell.cmpgt(Vec3::ZERO).all(),
            "FlatTorus3 cell must be finite and positive, got {cell:?}"
        );
        Self { cell }
    }

    /// Cubic cell of the given side length.
    pub fn cube(side: f32) -> Self {
        Self::new(Vec3::splat(side))
    }

    /// The three side lengths of the fundamental box; finite and strictly
    /// positive, since that is checked on construction.
    pub fn cell(&self) -> Vec3 {
        self.cell
    }

    /// Largest radius within which [`Space::exp`] is injective and
    /// `log(from, exp(from, v)) == v`. Half the shortest lattice vector.
    pub fn injectivity_radius(&self) -> f32 {
        0.5 * self.cell.min_element()
    }

    /// Integer lattice coordinates of the cell containing `p`, as an
    /// integral-valued `Vec3`.
    ///
    /// `floor(p/c + 1/2)` alone is not enough: when `pᵢ` sits an ulp inside the
    /// upper face, `pᵢ/cᵢ` can round up onto the tie and send the index one cell
    /// too far, putting the representative outside the domain. The correction
    /// tests the residual that was actually computed rather than the exact
    /// quotient, so it closes the case the rounding created; the residual is
    /// never more than one cell out, so one step suffices.
    fn lattice_index(&self, p: Vec3) -> Vec3 {
        let index = (p / self.cell + Vec3::splat(0.5)).floor();
        let residual = p - self.cell * index;
        let half = 0.5 * self.cell;
        index - unit_where(residual.cmplt(-half)) + unit_where(residual.cmpge(half))
    }

    /// The canonical lift of `p`'s orbit.
    fn wrap(&self, p: Vec3) -> Vec3 {
        p - self.cell * self.lattice_index(p)
    }
}

fn unit_where(mask: BVec3) -> Vec3 {
    Vec3::select(mask, Vec3::ONE, Vec3::ZERO)
}

impl Space for FlatTorus3 {
    type Point = Vec3;
    type Vector = Vec3;

    /// Geodesic distance in the quotient: the length of the shortest lift of
    /// `a - b`, i.e. `min over λ in Λ of |a - b - λ|`.
    fn distance(&self, a: Vec3, b: Vec3) -> f32 {
        self.wrap(a - b).length()
    }

    /// Travel from `at` along the geodesic and return the *canonical* lift of
    /// the endpoint. Canonicalizing here is what makes stepped ray continuation
    /// and a single long geodesic agree without a portal test at the caller.
    fn exp(&self, at: Vec3, v: Vec3) -> Vec3 {
        self.wrap(at + v)
    }

    /// The shortest tangent vector reaching `to`'s orbit from `from`.
    ///
    /// Multivalued on the quotient; this branch takes the minimal
    /// representative. It is discontinuous across the cut locus (the faces of
    /// the domain centered on `from`), and `exp(from, log(from, to)) == to` only
    /// for `to` within [`FlatTorus3::injectivity_radius`] of `from`.
    fn log(&self, from: Vec3, to: Vec3) -> Vec3 {
        self.wrap(to - from)
    }

    fn parallel_transport(&self, _from: Vec3, _to: Vec3, v: Vec3) -> Vec3 {
        // Zero curvature: transport is the identity along every path, so the
        // holonomy of the quotient is trivial despite its nontrivial pi_1.
        v
    }

    /// False despite zero curvature. `is_chart_flat` licenses raw chart
    /// arithmetic as the geometry, and chart arithmetic is not Λ-periodic:
    /// `dot(p, n) - d` disagrees with the quotient across the gluing.
    fn is_chart_flat(&self) -> bool {
        false
    }
}

impl IsometryGroup for FlatTorus3 {
    type Iso = Iso3;

    fn iso_identity(&self) -> Iso3 {
        Iso3::IDENTITY
    }

    fn iso_compose(&self, a: Iso3, b: Iso3) -> Iso3 {
        Iso3 {
            rotation: a.rotation * b.rotation,
            translation: a.rotation * b.translation + a.translation,
        }
    }

    fn iso_inverse(&self, a: Iso3) -> Iso3 {
        let inverse_rotation = a.rotation.inverse();
        Iso3 {
            rotation: inverse_rotation,
            translation: inverse_rotation * (-a.translation),
        }
    }

    /// Acts on lifts, in the cover. No canonicalization: see the module doc.
    fn iso_apply(&self, iso: Iso3, p: Vec3) -> Vec3 {
        iso.rotation * p + iso.translation
    }

    fn iso_transport(&self, iso: Iso3, _at: Vec3, v: Vec3) -> Vec3 {
        iso.rotation * v
    }
}

impl QuotientSpace for FlatTorus3 {
    fn face_pairings(&self) -> impl Iterator<Item = Iso3> {
        [
            Iso3::from_translation(Vec3::new(self.cell.x, 0.0, 0.0)),
            Iso3::from_translation(Vec3::new(0.0, self.cell.y, 0.0)),
            Iso3::from_translation(Vec3::new(0.0, 0.0, self.cell.z)),
        ]
        .into_iter()
    }

    fn in_fundamental_domain(&self, p: Vec3) -> bool {
        let half = 0.5 * self.cell;
        p.cmpge(-half).all() && p.cmplt(half).all()
    }

    fn wrap_to_domain(&self, p: Vec3) -> (Vec3, Iso3) {
        let translation = -(self.cell * self.lattice_index(p));
        // `iso_apply` adds this translation to `p`, reproducing `wrap`'s
        // subtraction bit for bit; the postcondition is an identity, not an
        // approximation.
        (p + translation, Iso3::from_translation(translation))
    }
}

impl WgslSpace for FlatTorus3 {
    fn wgsl_impl(&self) -> Cow<'static, str> {
        Cow::Owned(flat_torus3_wgsl(self.cell))
    }
}

/// Prelude mirroring [`FlatTorus3`]'s Rust arithmetic expression for
/// expression, including the lattice-index correction.
///
/// Parity is to one ulp of the cell scale, not bitwise: a shader compiler may
/// contract the multiply-add that forms the residual. Off the faces that is an
/// ulp; on a face it decides which of two representatives comes back, so the
/// GPU can return the lift one cell over. Both name the same point of the
/// quotient, which is the only claim callers may rely on across the boundary.
///
/// `{:?}` on `f32` prints the shortest literal that round-trips and always
/// carries a decimal point or exponent, so the baked cell parses back to the
/// exact input bits.
fn flat_torus3_wgsl(cell: Vec3) -> String {
    let (cx, cy, cz) = (cell.x, cell.y, cell.z);
    let (hx, hy, hz) = (0.5 * cell.x, 0.5 * cell.y, 0.5 * cell.z);
    format!(
        r#"
// loam-math :: FlatTorus3 (v0 Space WGSL ABI)
// Unbounded arc: the quotient is compact, so the march kernel's boundary
// escape must never fire.
const LOAM_MAX_ARC: f32 = 1e9;
const LOAM_TORUS_CELL: vec3<f32> = vec3<f32>({cx:?}, {cy:?}, {cz:?});
const LOAM_TORUS_HALF: vec3<f32> = vec3<f32>({hx:?}, {hy:?}, {hz:?});

fn loam_torus_index(p: vec3<f32>) -> vec3<f32> {{
    let index = floor(p / LOAM_TORUS_CELL + vec3<f32>(0.5));
    let residual = p - LOAM_TORUS_CELL * index;
    let below = select(vec3<f32>(0.0), vec3<f32>(1.0), residual < -LOAM_TORUS_HALF);
    let above = select(vec3<f32>(0.0), vec3<f32>(1.0), residual >= LOAM_TORUS_HALF);
    return index - below + above;
}}

fn loam_torus_wrap(p: vec3<f32>) -> vec3<f32> {{
    return p - LOAM_TORUS_CELL * loam_torus_index(p);
}}

fn loam_distance(a: vec3<f32>, b: vec3<f32>) -> f32 {{ return length(loam_torus_wrap(a - b)); }}
fn loam_origin_distance(p: vec3<f32>) -> f32 {{ return length(loam_torus_wrap(p)); }}
fn loam_exp(at: vec3<f32>, v: vec3<f32>) -> vec3<f32> {{ return loam_torus_wrap(at + v); }}
fn loam_log(p_from: vec3<f32>, p_to: vec3<f32>) -> vec3<f32> {{ return loam_torus_wrap(p_to - p_from); }}
fn loam_parallel_transport(p_from: vec3<f32>, p_to: vec3<f32>, v: vec3<f32>) -> vec3<f32> {{ return v; }}
"#
    )
}

/// The cover every [`LensSpace`] quotients. Metric primitives are computed
/// there and pushed down: a quotient changes which lift they are handed, never
/// the formula.
const COVER: SphericalS3Embedded = SphericalS3Embedded;

/// The lens space `L(p, q) = S³/Z_p`.
///
/// The deck group is generated by the double rotation
/// `g·(z₁, z₂) = (e^(2πi/p)·z₁, e^(2πi·q/p)·z₂)` of S³ ⊂ C², writing
/// `z₁ = x + iy` and `z₂ = z + iw` (Rolfsen, *Knots and Links*, 1976, §9.B;
/// Hatcher, *Algebraic Topology*, 2002, Example 2.43). `gcd(p, q) = 1` makes
/// the action free, so the quotient is a closed 3-manifold carrying the round
/// metric unchanged: curvature `K = +1` and geodesics that are great circles
/// of the cover.
///
/// The cover is [`SphericalS3Embedded`], so a `Point` is one of its unit
/// `Vec4` lifts. The hemisphere chart [`crate::SphericalS3`] cannot host this
/// quotient: it represents only `w ≥ 0`, and a deck element carries lifts
/// across the equator, which is where the whole point of
/// [`IsometryGroup::iso_apply`] acting on the cover would be lost.
///
/// The fundamental domain is the wedge `arg(z₁) ∈ [-π/p, π/p)`, the Dirichlet
/// domain of `Vec4::X`. That base point has `z₂ = 0`, so its orbit is the p-th
/// roots of unity on the `z₁` circle and
/// `⟨x, g^k·X⟩ = |z₁|·cos(arg(z₁) - k·2π/p)` is largest at the nearest
/// multiple of `2π/p`; the domain therefore has exactly two faces, glued by
/// the single generator [`QuotientSpace::face_pairings`] returns. `q` lives in
/// the gluing rather than in the shape of the domain, which is the classical
/// lens picture.
///
/// Off the circle `z₁ = 0` that domain is strict. On it `arg(z₁)` is
/// undefined, every member of the orbit tests as canonical, and
/// [`QuotientSpace::wrap_to_domain`] returns its input. That circle is the
/// edge where the p wedges meet; it is measure zero and no geodesic sampled
/// off it reaches it.
///
/// The other numerical limit is the wedge walls themselves. A deck element
/// acts by an irrational rotation, so unlike [`FlatTorus3`]'s exact lattice
/// subtraction it cannot place a representative on a wall to better than the
/// rounding of that rotation and of `atan2`, a few ulps of the argument. A
/// lift within that of a wall has both of its wall representatives within the
/// same distance of the domain, and which one comes back is not determined at
/// f32. Both are lifts of the same point, so nothing downstream can tell.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LensSpace {
    p: u32,
    q: u32,
}

impl LensSpace {
    /// `q` is reduced mod `p`; `gcd(p, q)` must be 1 or the action has fixed
    /// points and the quotient is not a manifold.
    ///
    /// `p = 1` is rejected rather than admitted as the trivial quotient: it is
    /// S³, which [`SphericalS3Embedded`] already is, and a second spelling of
    /// one geometry is a cost this crate has paid once already.
    pub fn new(p: u32, q: u32) -> Self {
        assert!(p >= 2, "LensSpace needs p >= 2, got p = {p}");
        let q = q % p;
        assert!(
            gcd(p, q) == 1,
            "LensSpace needs gcd(p, q) = 1 for a free action, got p = {p}, q = {q}"
        );
        Self { p, q }
    }

    /// Order of the deck group.
    pub fn p(&self) -> u32 {
        self.p
    }

    /// Twist of the gluing, reduced mod `p`.
    pub fn q(&self) -> u32 {
        self.q
    }

    /// Largest radius within which [`Space::exp`] is injective: `π/p`.
    ///
    /// `g^k` displaces `x` by `acos(|z₁|²·cos(k·β₁) + |z₂|²·cos(k·β₂))`, a
    /// convex combination of the two plane angles, so its minimum over S³ is
    /// the smaller of them. Over `k ≠ 0` that minimum is `2π/p`, attained at
    /// `k = 1` in the `z₁` plane, and the injectivity radius is half of it.
    pub fn injectivity_radius(&self) -> f32 {
        PI / self.p as f32
    }

    /// `g^power`: the deck element advancing `arg(z₁)` by `power·2π/p` and
    /// `arg(z₂)` by `power·q·2π/p`.
    ///
    /// The power is reduced mod `p` in integers before it reaches the
    /// trigonometry, so `deck(0)` is exactly the identity matrix and a large
    /// power costs no accuracy.
    pub fn deck(&self, power: i32) -> Iso4 {
        let (beta1, beta2) = self.deck_angles(power);
        let (sin1, cos1) = beta1.sin_cos();
        let (sin2, cos2) = beta2.sin_cos();
        Iso4 {
            matrix: Mat4::from_cols(
                Vec4::new(cos1, sin1, 0.0, 0.0),
                Vec4::new(-sin1, cos1, 0.0, 0.0),
                Vec4::new(0.0, 0.0, cos2, sin2),
                Vec4::new(0.0, 0.0, -sin2, cos2),
            ),
        }
    }

    /// Rotation angles of `g^power` in the `z₁` and `z₂` planes.
    fn deck_angles(&self, power: i32) -> (f32, f32) {
        let p = self.p as i64;
        let k = (power as i64).rem_euclid(p);
        let step = TAU / self.p as f32;
        (step * k as f32, step * ((k * self.q as i64) % p) as f32)
    }

    /// Wedges of `2π/p` between `x` and the fundamental domain, offset by a
    /// half so that `floor` of it is the wedge index and zero names the
    /// domain. One expression feeds both [`QuotientSpace::in_fundamental_domain`]
    /// and [`QuotientSpace::wrap_to_domain`], so membership is the wrap's
    /// fixpoint set by construction rather than by a second opinion that
    /// disagrees an ulp from the wall.
    ///
    /// `atan2(0, 0) = 0` is what puts the circle `z₁ = 0` in the domain.
    fn wedge_parameter(&self, x: Vec4) -> f32 {
        x.y.atan2(x.x) * (self.p as f32 / TAU) + 0.5
    }

    /// Deck power carrying `x` into the fundamental domain.
    fn wedge_offset(&self, x: Vec4) -> i32 {
        -(self.wedge_parameter(x).floor() as i32)
    }

    /// The deck power minimising `d(from, g^power·to)`, that lift, and the
    /// distance to it: the quotient's metric, `log` and transport all need the
    /// same three numbers and one pass finds them.
    ///
    /// Ties go to the smallest non-negative power, so the branch is a pure
    /// function of its inputs. `O(p)`: the two plane angles advance at
    /// unrelated rates, so the maximiser of `⟨x, g^k·y⟩` has no closed form,
    /// unlike the wrap, where one endpoint is the domain's own centre.
    fn nearest_lift(&self, from: Vec4, to: Vec4) -> (i32, Vec4, f32) {
        let mut best_lift = self.iso_apply(self.deck(0), to);
        let mut best_power = 0;
        let mut best_distance = COVER.distance(from, best_lift);
        for power in 1..self.p as i32 {
            let lift = self.iso_apply(self.deck(power), to);
            let distance = COVER.distance(from, lift);
            if distance < best_distance {
                best_lift = lift;
                best_power = power;
                best_distance = distance;
            }
        }
        (best_power, best_lift, best_distance)
    }

    /// WGSL for the ambient-S³ deck arithmetic: the group action, the wrap and
    /// the Γ-invariant distance.
    ///
    /// Not [`WgslSpace`]. That ABI is `vec3<f32>` and no vec3 chart of S³
    /// holds this quotient's deck images, so a consumer marches in the ambient
    /// `vec4<f32>` instead, where a geodesic is a plane rotation and stepping
    /// carries no truncation error at all.
    ///
    /// The per-power sines and cosines are baked from [`LensSpace::deck`], so
    /// the shader consumes the same f32 rotation coefficients the CPU
    /// computes; what is left to diverge is the multiply-add rounding a shader
    /// compiler may contract, which is an ulp of the coordinate. `{:?}` on
    /// `f32` prints the shortest literal that round-trips and always carries a
    /// decimal point or exponent, so each coefficient parses back to the exact
    /// input bits.
    pub fn wgsl_prelude(&self) -> String {
        let (p, q) = (self.p, self.q);
        let wedges_per_turn = self.p as f32 / TAU;
        let table = (0..self.p as i32)
            .map(|power| {
                let m = self.deck(power).matrix;
                format!(
                    "vec4<f32>({:?}, {:?}, {:?}, {:?})",
                    m.x_axis.x, m.x_axis.y, m.z_axis.z, m.z_axis.w
                )
            })
            .collect::<Vec<_>>()
            .join(",\n    ");
        format!(
            r#"
// loam-math :: LensSpace L({p}, {q}), ambient S³
// Points are unit vec4 with z1 = (x, y) and z2 = (z, w). Deck powers index
// LOAM_LENS_DECK, whose entries are (cos b1, sin b1, cos b2, sin b2).
const LOAM_LENS_P: i32 = {p};
const LOAM_LENS_WEDGES_PER_TURN: f32 = {wedges_per_turn:?};
const LOAM_LENS_DECK = array<vec4<f32>, {p}>(
    {table}
);

fn loam_lens_apply(x: vec4<f32>, power: i32) -> vec4<f32> {{
    let k = ((power % LOAM_LENS_P) + LOAM_LENS_P) % LOAM_LENS_P;
    let d = LOAM_LENS_DECK[k];
    return normalize(vec4<f32>(
        x.x * d.x - x.y * d.y,
        x.x * d.y + x.y * d.x,
        x.z * d.z - x.w * d.w,
        x.z * d.w + x.w * d.z,
    ));
}}

fn loam_lens_wedge_offset(x: vec4<f32>) -> i32 {{
    return -i32(floor(atan2(x.y, x.x) * LOAM_LENS_WEDGES_PER_TURN + 0.5));
}}

fn loam_lens_wrap(x: vec4<f32>) -> vec4<f32> {{
    var power = loam_lens_wedge_offset(x);
    var wrapped = loam_lens_apply(x, power);
    let correction = loam_lens_wedge_offset(wrapped);
    if correction != 0 {{
        power += correction;
        wrapped = loam_lens_apply(x, power);
    }}
    return wrapped;
}}

// Chord half-angle, minimised over the deck group: the quotient distance.
// Minimising the chord and minimising its arc are the same argmin, so the
// asin runs once instead of p times.
fn loam_lens_distance(a: vec4<f32>, b: vec4<f32>) -> f32 {{
    var best = 2.0;
    for (var k = 0; k < LOAM_LENS_P; k = k + 1) {{
        best = min(best, length(a - loam_lens_apply(b, k)) * 0.5);
    }}
    return 2.0 * asin(clamp(best, 0.0, 1.0));
}}

fn loam_lens_nearest_power(a: vec4<f32>, b: vec4<f32>) -> i32 {{
    var best = 2.0;
    var power = 0;
    for (var k = 0; k < LOAM_LENS_P; k = k + 1) {{
        let half_chord = length(a - loam_lens_apply(b, k)) * 0.5;
        if half_chord < best {{
            best = half_chord;
            power = k;
        }}
    }}
    return power;
}}
"#
        )
    }
}

/// Euclid's algorithm (Knuth, *TAOCP* vol. 2, 3rd ed., §4.5.2).
fn gcd(a: u32, b: u32) -> u32 {
    if b == 0 {
        a
    } else {
        gcd(b, a % b)
    }
}

impl Space for LensSpace {
    type Point = Vec4;
    type Vector = Vec4;

    /// `min over k of d_S³(a, g^k·b)`, the length of the shortest path in the
    /// quotient.
    fn distance(&self, a: Vec4, b: Vec4) -> f32 {
        self.nearest_lift(a, b).2
    }

    /// Travel the cover's great circle and return the *canonical* lift of the
    /// endpoint. Canonicalising here is what lets a stepped ray march and a
    /// single long geodesic agree without a portal test at the caller.
    fn exp(&self, at: Vec4, v: Vec4) -> Vec4 {
        self.wrap_to_domain(COVER.exp(at, v)).0
    }

    /// The shortest tangent at `from` reaching `to`'s orbit.
    ///
    /// Multivalued on the quotient; this branch takes the minimal
    /// representative, so it is discontinuous across the cut locus and
    /// `exp(from, log(from, to)) == to` holds as a statement about orbits, not
    /// about lifts.
    fn log(&self, from: Vec4, to: Vec4) -> Vec4 {
        let (_, lift, _) = self.nearest_lift(from, to);
        COVER.log(from, lift)
    }

    /// Transport along the minimal geodesic of the quotient.
    fn parallel_transport(&self, from: Vec4, to: Vec4, v: Vec4) -> Vec4 {
        let (power, lift, _) = self.nearest_lift(from, to);
        let carried = COVER.parallel_transport(from, lift, v);
        // `carried` is a tangent at `g^power·to`. The differential of a deck
        // element is its own matrix, so the inverse power brings the vector
        // back to the lift the caller actually named.
        self.iso_transport(self.deck(-power), lift, carried)
    }
}

impl IsometryGroup for LensSpace {
    type Iso = Iso4;

    fn iso_identity(&self) -> Iso4 {
        COVER.iso_identity()
    }

    fn iso_compose(&self, a: Iso4, b: Iso4) -> Iso4 {
        COVER.iso_compose(a, b)
    }

    fn iso_inverse(&self, a: Iso4) -> Iso4 {
        COVER.iso_inverse(a)
    }

    /// Acts on lifts, in the cover. No canonicalisation: see the module doc.
    ///
    /// An `Iso4` descends to the quotient exactly when it normalises the deck
    /// group. The two-torus of rotations in the `z₁` and `z₂` planes always
    /// does, `diag(1, -1, 1, -1)` does by sending `g` to `g⁻¹`, and the whole
    /// of U(2) does when `q = 1`. Nothing here enforces it: the group law and
    /// the metric invariance are properties of the cover, which hold for every
    /// SO(4) element, and only a caller wanting the action to descend needs
    /// the normaliser.
    fn iso_apply(&self, iso: Iso4, p: Vec4) -> Vec4 {
        COVER.iso_apply(iso, p)
    }

    fn iso_transport(&self, iso: Iso4, at: Vec4, v: Vec4) -> Vec4 {
        COVER.iso_transport(iso, at, v)
    }
}

impl QuotientSpace for LensSpace {
    /// One generator: the lens has exactly two faces and `g` carries the
    /// domain across the `+arg(z₁)` one, its inverse across the other.
    fn face_pairings(&self) -> impl Iterator<Item = Iso4> {
        std::iter::once(self.deck(1))
    }

    fn in_fundamental_domain(&self, p: Vec4) -> bool {
        (0.0..1.0).contains(&self.wedge_parameter(p))
    }

    fn wrap_to_domain(&self, p: Vec4) -> (Vec4, Iso4) {
        let mut power = self.wedge_offset(p);
        let mut deck = self.deck(power);
        let mut wrapped = self.iso_apply(deck, p);
        // The rotation rounds, so `wrapped` can land an ulp of argument past
        // the wall it was aimed at. Correcting against the representative that
        // was actually computed closes that case whenever the neighbouring
        // wedge lands strictly inside; the residual is under one wedge, so one
        // step suffices. It cannot close the case where the lift sits on a
        // wall to within the rotation's own rounding, which is the limit the
        // type doc states. Recomputing from `p` rather than composing keeps
        // the returned deck element exact.
        let correction = self.wedge_offset(wrapped);
        if correction != 0 {
            power += correction;
            deck = self.deck(power);
            wrapped = self.iso_apply(deck, p);
        }
        (wrapped, deck)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;

    const CELL: Vec3 = Vec3::new(2.0, 3.0, 1.5);

    fn torus() -> FlatTorus3 {
        FlatTorus3::new(CELL)
    }

    /// xorshift32; the sweeps below need a few 10⁵ deterministic samples and a
    /// seeded generator is the only kind allowed in this crate's tests.
    pub(super) struct Xorshift(pub(super) u32);

    impl Xorshift {
        pub(super) fn next_u32(&mut self) -> u32 {
            self.0 ^= self.0 << 13;
            self.0 ^= self.0 >> 17;
            self.0 ^= self.0 << 5;
            self.0
        }

        /// Uniform in `[-span, span)`.
        pub(super) fn signed(&mut self, span: f32) -> f32 {
            let unit = self.next_u32() as f32 / u32::MAX as f32;
            (unit * 2.0 - 1.0) * span
        }

        fn point(&mut self, span: f32) -> Vec3 {
            Vec3::new(self.signed(span), self.signed(span), self.signed(span))
        }
    }

    /// Lifts chosen to stress the rounding the lattice-index correction exists
    /// for: exact face coordinates, an ulp either side of them, and exact
    /// lattice translates of all three.
    fn boundary_lifts(cell: Vec3) -> Vec<Vec3> {
        let half = 0.5 * cell;
        let mut lifts = Vec::new();
        for axis in 0..3 {
            for sign in [-1.0_f32, 1.0] {
                let edge = sign * half[axis];
                for coordinate in [
                    edge,
                    f32::from_bits(edge.to_bits() - 1),
                    f32::from_bits(edge.to_bits() + 1),
                ] {
                    for copy in -3..=3 {
                        let mut p = Vec3::new(0.25, -0.5, 0.125);
                        p[axis] = coordinate + copy as f32 * cell[axis];
                        lifts.push(p);
                    }
                }
            }
        }
        lifts
    }

    #[test]
    fn wrap_lands_every_lift_in_the_half_open_fundamental_domain() {
        let t = torus();
        let mut rng = Xorshift(0x5eed_1234);
        let mut lifts = boundary_lifts(CELL);
        for _ in 0..200_000 {
            lifts.push(rng.point(40.0));
        }
        for p in lifts {
            let (q, _) = t.wrap_to_domain(p);
            assert!(
                t.in_fundamental_domain(q),
                "wrap({p:?}) = {q:?} escaped the domain of cell {CELL:?}"
            );
        }
    }

    #[test]
    fn fundamental_domain_membership_is_exactly_the_wrap_fixpoint() {
        let t = torus();
        let mut rng = Xorshift(0x1337_beef);
        for _ in 0..50_000 {
            let p = rng.point(6.0);
            let (q, _) = t.wrap_to_domain(p);
            assert_eq!(t.in_fundamental_domain(p), p == q, "at {p:?}");
        }
    }

    #[test]
    fn the_returned_deck_element_reproduces_the_representative_exactly() {
        let t = torus();
        let mut rng = Xorshift(0x0bad_f00d);
        let mut lifts = boundary_lifts(CELL);
        for _ in 0..50_000 {
            lifts.push(rng.point(25.0));
        }
        for p in lifts {
            let (q, g) = t.wrap_to_domain(p);
            assert_eq!(t.iso_apply(g, p), q, "deck element disagreed at {p:?}");
        }
    }

    #[test]
    fn wrapping_an_interior_point_returns_the_identity_deck_element() {
        let t = torus();
        let p = Vec3::new(0.3, -1.1, 0.4);
        let (q, g) = t.wrap_to_domain(p);
        assert_eq!(q, p);
        assert_eq!(g, Iso3::IDENTITY);
    }

    #[test]
    fn face_pairings_are_the_three_positive_lattice_translations() {
        let t = torus();
        let pairings: Vec<Iso3> = t.face_pairings().collect();
        assert_eq!(pairings.len(), 3);
        for (axis, pairing) in pairings.iter().enumerate() {
            let mut expected = Vec3::ZERO;
            expected[axis] = CELL[axis];
            assert_eq!(pairing.translation, expected);
            assert_eq!(pairing.rotation, glam::Quat::IDENTITY);
            assert_eq!(t.iso_inverse(*pairing).translation, -expected);
        }
    }

    #[test]
    fn deck_group_composition_is_a_group_action_on_lifts() {
        let t = torus();
        let generators: Vec<Iso3> = t
            .face_pairings()
            .flat_map(|g| [g, t.iso_inverse(g)])
            .collect();
        let mut rng = Xorshift(0xfeed_face);

        for _ in 0..20_000 {
            let a = word(&t, &generators, &mut rng);
            let b = word(&t, &generators, &mut rng);
            let p = rng.point(8.0);

            let sequential = t.iso_apply(a, t.iso_apply(b, p));
            let composed = t.iso_apply(t.iso_compose(a, b), p);
            assert_relative_eq!(sequential.x, composed.x, epsilon = 1e-5);
            assert_relative_eq!(sequential.y, composed.y, epsilon = 1e-5);
            assert_relative_eq!(sequential.z, composed.z, epsilon = 1e-5);

            assert_eq!(t.iso_apply(t.iso_identity(), p), p);

            let round_trip = t.iso_apply(t.iso_inverse(a), t.iso_apply(a, p));
            assert_relative_eq!(round_trip.x, p.x, epsilon = 1e-5);
            assert_relative_eq!(round_trip.y, p.y, epsilon = 1e-5);
            assert_relative_eq!(round_trip.z, p.z, epsilon = 1e-5);
        }
    }

    fn word(t: &FlatTorus3, generators: &[Iso3], rng: &mut Xorshift) -> Iso3 {
        let length = (rng.next_u32() % 5) as usize;
        (0..length).fold(t.iso_identity(), |accumulated, _| {
            let pick = generators[(rng.next_u32() as usize) % generators.len()];
            t.iso_compose(accumulated, pick)
        })
    }

    #[test]
    fn wrap_is_invariant_under_the_deck_group() {
        let t = torus();
        let generators: Vec<Iso3> = t
            .face_pairings()
            .flat_map(|g| [g, t.iso_inverse(g)])
            .collect();
        let mut rng = Xorshift(0x00c0_ffee);
        for _ in 0..20_000 {
            let p = rng.point(5.0);
            let (q, _) = t.wrap_to_domain(p);
            let g = word(&t, &generators, &mut rng);
            let (q_translated, _) = t.wrap_to_domain(t.iso_apply(g, p));
            assert_relative_eq!(q_translated.x, q.x, epsilon = 1e-4);
            assert_relative_eq!(q_translated.y, q.y, epsilon = 1e-4);
            assert_relative_eq!(q_translated.z, q.z, epsilon = 1e-4);
        }
    }

    #[test]
    fn distance_is_the_minimum_over_the_lattice() {
        let t = torus();
        let mut rng = Xorshift(0xdead_10cc);
        for _ in 0..20_000 {
            let a = rng.point(4.0);
            let b = rng.point(4.0);
            let center = ((a - b) / CELL).round();
            let mut brute = f32::INFINITY;
            for i in -3..=3 {
                for j in -3..=3 {
                    for k in -3..=3 {
                        let offset = Vec3::new(i as f32, j as f32, k as f32);
                        brute = brute.min((a - b - CELL * (center + offset)).length());
                    }
                }
            }
            assert_relative_eq!(t.distance(a, b), brute, epsilon = 1e-5);
        }
    }

    #[test]
    fn distance_is_lattice_invariant_symmetric_and_zero_on_the_orbit() {
        let t = torus();
        let generators: Vec<Iso3> = t
            .face_pairings()
            .flat_map(|g| [g, t.iso_inverse(g)])
            .collect();
        let mut rng = Xorshift(0x9e37_79b9);
        for _ in 0..20_000 {
            let a = rng.point(4.0);
            let b = rng.point(4.0);
            let g = word(&t, &generators, &mut rng);

            assert_relative_eq!(t.distance(a, b), t.distance(b, a));
            assert_relative_eq!(
                t.distance(t.iso_apply(g, a), b),
                t.distance(a, b),
                epsilon = 1e-4
            );
            assert_relative_eq!(t.distance(a, t.iso_apply(g, a)), 0.0, epsilon = 1e-4);
        }
    }

    #[test]
    fn distance_never_exceeds_half_the_cell_diagonal() {
        let t = torus();
        let bound = (0.5 * CELL).length();
        let mut rng = Xorshift(0x2545_f491);
        for _ in 0..50_000 {
            let d = t.distance(rng.point(30.0), rng.point(30.0));
            assert!(d <= bound + 1e-5, "{d} exceeded the diameter bound {bound}");
        }
    }

    #[test]
    fn distance_satisfies_the_triangle_inequality() {
        let t = torus();
        let mut rng = Xorshift(0x7f4a_7c15);
        for _ in 0..50_000 {
            let a = rng.point(5.0);
            let b = rng.point(5.0);
            let c = rng.point(5.0);
            assert!(t.distance(a, c) <= t.distance(a, b) + t.distance(b, c) + 1e-4);
        }
    }

    #[test]
    fn crossing_a_face_re_enters_through_the_opposite_face() {
        let t = torus();
        let half = 0.5 * CELL;
        let overshoot = 0.01;
        for axis in 0..3 {
            let mut start = Vec3::new(0.4, -0.7, 0.2);
            start[axis] = half[axis] - overshoot;
            let mut step = Vec3::ZERO;
            step[axis] = 2.0 * overshoot;

            let arrived = t.exp(start, step);
            assert!(t.in_fundamental_domain(arrived));
            assert_relative_eq!(arrived[axis], -half[axis] + overshoot, epsilon = 1e-6);
            for other in 0..3 {
                if other != axis {
                    assert_relative_eq!(arrived[other], start[other]);
                }
            }
        }
    }

    #[test]
    fn a_geodesic_crossing_the_gluing_lands_where_the_face_pairing_says() {
        let t = torus();
        let half = 0.5 * CELL;
        let pairings: Vec<Iso3> = t.face_pairings().collect();

        for (axis, pairing) in pairings.iter().enumerate() {
            let mut start = Vec3::new(0.1, 0.9, -0.3);
            start[axis] = half[axis] - 0.05;
            let mut step = Vec3::ZERO;
            step[axis] = 0.2;

            let uncorrected = start + step;
            let (arrived, deck) = t.wrap_to_domain(uncorrected);

            // Exiting through the +axis face applies the inverse pairing.
            let expected = t.iso_inverse(*pairing);
            assert_eq!(deck.translation, expected.translation, "axis {axis}");
            assert_eq!(t.iso_apply(expected, uncorrected), arrived);
            assert_eq!(t.exp(start, step), arrived);
        }
    }

    #[test]
    fn stepped_ray_continuation_matches_a_single_geodesic_exp() {
        let t = torus();
        let mut rng = Xorshift(0x4d59_5f21);
        for _ in 0..5_000 {
            let start = t.wrap(rng.point(1.5));
            let velocity = rng.point(4.0);

            let direct = t.exp(start, velocity);

            const STEPS: usize = 64;
            let mut marched = start;
            for _ in 0..STEPS {
                marched = t.exp(marched, velocity / STEPS as f32);
            }

            // 64 wraps each contribute at most a cell-scaled rounding; the
            // bound is the accumulated worst case, not a fudge factor.
            let residual = t.distance(direct, marched);
            assert!(
                residual < 64.0 * f32::EPSILON * CELL.max_element() * 8.0,
                "stepped {marched:?} vs direct {direct:?}, residual {residual}"
            );
        }
    }

    #[test]
    fn exp_and_log_invert_exactly_within_the_injectivity_radius() {
        let t = torus();
        let radius = t.injectivity_radius();
        assert_relative_eq!(radius, 0.75);

        let mut rng = Xorshift(0x6c07_8965);
        for _ in 0..20_000 {
            let from = t.wrap(rng.point(2.0));
            let direction = rng.point(1.0).normalize_or_zero();
            let v = direction * (0.95 * radius);
            let to = t.exp(from, v);
            let recovered = t.log(from, to);
            assert_relative_eq!(recovered.x, v.x, epsilon = 1e-5);
            assert_relative_eq!(recovered.y, v.y, epsilon = 1e-5);
            assert_relative_eq!(recovered.z, v.z, epsilon = 1e-5);
        }

        // Past the radius the short way home is a different vector: two units
        // along y in a cell of three wraps to one unit backwards.
        let short = t.log(Vec3::ZERO, t.exp(Vec3::ZERO, Vec3::new(0.0, 2.0, 0.0)));
        assert_relative_eq!(short.x, 0.0);
        assert_relative_eq!(short.y, -1.0);
        assert_relative_eq!(short.z, 0.0);
    }

    #[test]
    fn log_length_equals_quotient_distance() {
        let t = torus();
        let mut rng = Xorshift(0x1c69_b3f5);
        for _ in 0..50_000 {
            let a = rng.point(9.0);
            let b = rng.point(9.0);
            assert_relative_eq!(t.log(a, b).length(), t.distance(a, b));
        }
    }

    #[test]
    #[should_panic(expected = "must be finite and positive")]
    fn a_degenerate_cell_is_rejected_at_construction() {
        FlatTorus3::new(Vec3::new(1.0, 0.0, 1.0));
    }

    #[test]
    fn wgsl_prelude_exports_the_abi_and_bakes_a_round_tripping_cell() {
        let cell = Vec3::new(2.0, 3.0, 1.5e-7);
        let source = FlatTorus3::new(cell).wgsl_impl().into_owned();
        for symbol in [
            "fn loam_distance(",
            "fn loam_origin_distance(",
            "fn loam_exp(",
            "fn loam_log(",
            "fn loam_parallel_transport(",
            "fn loam_torus_wrap(",
            "const LOAM_MAX_ARC",
        ] {
            assert!(source.contains(symbol), "missing {symbol}");
        }

        let baked = source
            .split("const LOAM_TORUS_CELL: vec3<f32> = vec3<f32>(")
            .nth(1)
            .and_then(|rest| rest.split(')').next())
            .expect("cell is baked");
        let parsed: Vec<f32> = baked
            .split(", ")
            .map(|c| c.parse().expect("cell literal parses as f32"))
            .collect();
        assert_eq!(parsed, vec![cell.x, cell.y, cell.z], "emitted {baked}");
    }
}

#[cfg(test)]
mod lens_tests {
    use super::tests::Xorshift;
    use super::*;
    use approx::assert_relative_eq;

    /// Every (p, q) the sweeps run over: the two smallest quotients, a genuine
    /// twist, a larger order, and one with `q² ≡ 1 (mod p)`, the case whose
    /// isometry group is larger than the rest.
    const LENSES: &[(u32, u32)] = &[(2, 1), (3, 1), (5, 2), (7, 3), (8, 3)];

    /// Rejection sampling is not needed: normalising a cube sample biases
    /// toward the diagonals but still covers S³, and every property below is
    /// pointwise rather than distributional.
    fn unit4(rng: &mut Xorshift) -> Vec4 {
        let raw = Vec4::new(
            rng.signed(1.0),
            rng.signed(1.0),
            rng.signed(1.0),
            rng.signed(1.0),
        );
        if raw.length_squared() < 1e-6 {
            Vec4::X
        } else {
            raw.normalize()
        }
    }

    /// The deck generator built from first principles: two plane rotations by
    /// `2π/p` and `2πq/p`, raised by repeated multiplication. Independent of
    /// `LensSpace::deck_angles`'s modular reduction, so the sweeps below
    /// measure that reduction rather than restate it.
    fn generator_by_hand(p: u32, q: u32) -> Mat4 {
        let step = TAU / p as f32;
        let (sin1, cos1) = step.sin_cos();
        let (sin2, cos2) = (step * q as f32).sin_cos();
        Mat4::from_cols(
            Vec4::new(cos1, sin1, 0.0, 0.0),
            Vec4::new(-sin1, cos1, 0.0, 0.0),
            Vec4::new(0.0, 0.0, cos2, sin2),
            Vec4::new(0.0, 0.0, -sin2, cos2),
        )
    }

    /// Distance from a wedge wall at which which-wedge is still a determined
    /// question. Four decades above the rounding of the wrap's rotation and of
    /// `atan2`, a few ulps of an argument of order one;
    /// `a_lift_on_a_wedge_wall_comes_back_on_a_wall` covers what is under it.
    const WALL_MARGIN: f32 = 1e-4;

    /// Lifts a margin either side of every wedge wall, off both degenerate
    /// circles so each plane carries signal. These are what drive the wrap's
    /// correction step: the wedge each belongs to is determined, and it is the
    /// one the initial rounding can miss.
    fn wall_lifts(lens: &LensSpace) -> Vec<Vec4> {
        let mut lifts = Vec::new();
        for wedge in 0..lens.p() as i32 {
            let wall = (wedge as f32 + 0.5) * TAU / lens.p() as f32;
            for angle in [wall - WALL_MARGIN, wall + WALL_MARGIN] {
                let (sin, cos) = angle.sin_cos();
                lifts.push(Vec4::new(cos * 0.8, sin * 0.8, 0.5, 0.331_662_5).normalize());
            }
        }
        lifts
    }

    #[test]
    fn the_face_pairing_composes_to_the_identity_after_exactly_p_steps() {
        let mut rng = Xorshift(0x1e45_9ac1);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let generator = lens.face_pairings().next().expect("one face pairing");
            let samples: Vec<Vec4> = (0..32).map(|_| unit4(&mut rng)).collect();

            let mut accumulated = lens.iso_identity();
            for step in 1..=p {
                accumulated = lens.iso_compose(accumulated, generator);
                let moved = samples
                    .iter()
                    .map(|&x| SphericalS3Embedded.distance(lens.iso_apply(accumulated, x), x))
                    .fold(0.0f32, f32::max);
                if step == p {
                    assert!(
                        moved < 1e-5,
                        "L({p}, {q}): g^{step} moved a lift by {moved}, so the loop \
                         does not close"
                    );
                } else {
                    // Every sample has z1 != 0 with probability one, and a
                    // partial power turns that plane by a nonzero angle.
                    assert!(
                        moved > 0.1,
                        "L({p}, {q}): g^{step} already acts trivially, so the deck \
                         group has order {step}, not {p}"
                    );
                }
            }
        }
    }

    #[test]
    fn deck_powers_agree_with_repeated_composition_of_the_generator() {
        let mut rng = Xorshift(0x510c_2b77);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let by_hand = generator_by_hand(p, q);
            for power in -3 * p as i32..=3 * p as i32 {
                let mut composed = Mat4::IDENTITY;
                for _ in 0..power.rem_euclid(p as i32) {
                    composed = by_hand * composed;
                }
                for _ in 0..4 {
                    let x = unit4(&mut rng);
                    let want = (composed * x).normalize();
                    let got = lens.iso_apply(lens.deck(power), x);
                    assert!(
                        SphericalS3Embedded.distance(got, want) < 1e-4,
                        "L({p}, {q}): deck({power}) disagrees with the composed \
                         generator at {x:?}"
                    );
                }
            }
        }
    }

    #[test]
    fn the_twist_changes_the_metric_at_equal_order() {
        let untwisted = LensSpace::new(5, 1);
        let twisted = LensSpace::new(5, 2);
        let mut rng = Xorshift(0x2bad_1dea);
        let mut worst = 0.0f32;
        for _ in 0..2_000 {
            let a = unit4(&mut rng);
            let b = unit4(&mut rng);
            worst = worst.max((untwisted.distance(a, b) - twisted.distance(a, b)).abs());
        }
        assert!(
            worst > 0.1,
            "L(5, 1) and L(5, 2) returned the same metric to {worst}"
        );
    }

    #[test]
    fn the_order_changes_the_fundamental_domain() {
        let coarse = LensSpace::new(3, 1);
        let fine = LensSpace::new(7, 3);
        // arg(z1) = 0.6 rad: inside π/3 = 1.047, outside π/7 = 0.449.
        let (sin, cos) = 0.6_f32.sin_cos();
        let x = Vec4::new(cos * 0.9, sin * 0.9, 0.3, 0.335_410_2).normalize();
        assert!(coarse.in_fundamental_domain(x));
        assert!(!fine.in_fundamental_domain(x));
    }

    #[test]
    #[should_panic(expected = "gcd(p, q) = 1")]
    fn an_action_with_fixed_points_is_rejected_at_construction() {
        LensSpace::new(6, 2);
    }

    #[test]
    #[should_panic(expected = "p >= 2")]
    fn the_trivial_quotient_is_rejected_at_construction() {
        LensSpace::new(1, 0);
    }

    #[test]
    fn wrap_lands_every_lift_in_the_half_open_fundamental_domain() {
        let mut rng = Xorshift(0x5eed_1234);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let mut lifts = wall_lifts(&lens);
            lifts.extend((0..50_000).map(|_| unit4(&mut rng)));
            for x in lifts {
                let (wrapped, _) = lens.wrap_to_domain(x);
                assert!(
                    lens.in_fundamental_domain(wrapped),
                    "L({p}, {q}): wrap({x:?}) = {wrapped:?} escaped the domain"
                );
            }
        }
    }

    #[test]
    fn fundamental_domain_membership_is_exactly_the_wrap_fixpoint() {
        let mut rng = Xorshift(0x1337_beef);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let mut lifts = wall_lifts(&lens);
            lifts.extend((0..20_000).map(|_| unit4(&mut rng)));
            for x in lifts {
                let (wrapped, deck) = lens.wrap_to_domain(x);
                assert_eq!(
                    lens.in_fundamental_domain(x),
                    deck.matrix == Mat4::IDENTITY,
                    "L({p}, {q}) at {x:?}"
                );
                if lens.in_fundamental_domain(x) {
                    assert!(SphericalS3Embedded.distance(wrapped, x) < 1e-6);
                }
            }
        }
    }

    #[test]
    fn a_lift_on_a_wedge_wall_comes_back_on_a_wall() {
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let half = PI / p as f32;
            for wedge in 0..p as i32 {
                let wall = (wedge as f32 + 0.5) * TAU / p as f32;
                for angle in [
                    wall,
                    f32::from_bits(wall.to_bits() - 1),
                    f32::from_bits(wall.to_bits() + 1),
                ] {
                    let (sin, cos) = angle.sin_cos();
                    let x = Vec4::new(cos * 0.8, sin * 0.8, 0.5, 0.331_662_5).normalize();
                    let (wrapped, deck) = lens.wrap_to_domain(x);
                    assert_eq!(lens.iso_apply(deck, x), wrapped, "L({p}, {q}) at {angle}");
                    assert!(
                        (wrapped.y.atan2(wrapped.x).abs() - half).abs() < 1e-5,
                        "L({p}, {q}): a wall lift came back at {} rad, not on a wall \
                         at {half}",
                        wrapped.y.atan2(wrapped.x)
                    );
                }
            }
        }
    }

    #[test]
    fn the_returned_deck_element_reproduces_the_representative_exactly() {
        let mut rng = Xorshift(0x0bad_f00d);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let mut lifts = wall_lifts(&lens);
            lifts.extend((0..20_000).map(|_| unit4(&mut rng)));
            for x in lifts {
                let (wrapped, deck) = lens.wrap_to_domain(x);
                assert_eq!(
                    lens.iso_apply(deck, x),
                    wrapped,
                    "L({p}, {q}): deck element disagreed at {x:?}"
                );
            }
        }
    }

    #[test]
    fn wrap_is_invariant_under_the_deck_group() {
        let mut rng = Xorshift(0x00c0_ffee);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            for _ in 0..20_000 {
                let x = unit4(&mut rng);
                let power = (rng.next_u32() % (4 * p)) as i32 - 2 * p as i32;
                let (wrapped, _) = lens.wrap_to_domain(x);
                let (translated, _) = lens.wrap_to_domain(lens.iso_apply(lens.deck(power), x));
                assert!(
                    SphericalS3Embedded.distance(wrapped, translated) < 1e-3,
                    "L({p}, {q}): wrap of g^{power} x is a different lift at {x:?}"
                );
            }
        }
    }

    #[test]
    fn crossing_a_face_re_enters_through_the_opposite_face() {
        let mut rng = Xorshift(0x4d59_5f21);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let pairing = lens.face_pairings().next().expect("one face pairing");
            let half = PI / p as f32;
            let overshoot = 0.01;

            let (sin, cos) = (half + overshoot).sin_cos();
            let outside = Vec4::new(cos * 0.8, sin * 0.8, 0.5, 0.331_662_5).normalize();
            let (wrapped, deck) = lens.wrap_to_domain(outside);

            assert!(lens.in_fundamental_domain(wrapped));
            assert_relative_eq!(
                wrapped.y.atan2(wrapped.x),
                -half + overshoot,
                epsilon = 1e-5
            );
            // As an action, not as a matrix: at p = 2 the pairing is its own
            // inverse and the transpose reaches the same rotation through
            // sin(-π) rather than sin(π).
            let inverse = lens.iso_inverse(pairing);
            for _ in 0..64 {
                let x = unit4(&mut rng);
                assert!(
                    SphericalS3Embedded
                        .distance(lens.iso_apply(inverse, x), lens.iso_apply(deck, x))
                        < 1e-5,
                    "L({p}, {q}): the crossing's deck element is not the face pairing"
                );
            }
        }
    }

    #[test]
    fn a_rotation_mixing_the_two_planes_is_not_an_isometry_of_the_quotient() {
        let lens = LensSpace::new(5, 2);
        let (sin, cos) = 0.7_f32.sin_cos();
        // Rotation in the (x, w) plane: one coordinate from each factor.
        let mixing = Iso4 {
            matrix: Mat4::from_cols(
                Vec4::new(cos, 0.0, 0.0, sin),
                Vec4::Y,
                Vec4::Z,
                Vec4::new(-sin, 0.0, 0.0, cos),
            ),
        };
        let mut rng = Xorshift(0x6a_1c_45_09);
        let mut worst = 0.0f32;
        for _ in 0..2_000 {
            let a = unit4(&mut rng);
            let b = unit4(&mut rng);
            let moved = lens.distance(lens.iso_apply(mixing, a), lens.iso_apply(mixing, b));
            worst = worst.max((moved - lens.distance(a, b)).abs());
        }
        assert!(
            worst > 0.1,
            "a plane-mixing rotation preserved the quotient metric to {worst}, so \
             `distance` is not seeing the deck group"
        );
    }

    #[test]
    fn distance_is_the_minimum_over_the_deck_group() {
        let mut rng = Xorshift(0xdead_10cc);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let generator = generator_by_hand(p, q);
            for _ in 0..5_000 {
                let a = unit4(&mut rng);
                let b = unit4(&mut rng);
                let mut brute = f32::INFINITY;
                let mut lift = b;
                for _ in 0..p {
                    brute = brute.min(SphericalS3Embedded.distance(a, lift.normalize()));
                    lift = generator * lift;
                }
                assert_relative_eq!(lens.distance(a, b), brute, epsilon = 1e-4);
            }
        }
    }

    #[test]
    fn distance_is_deck_invariant_symmetric_and_zero_on_the_orbit() {
        let mut rng = Xorshift(0x9e37_79b9);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            for _ in 0..5_000 {
                let a = unit4(&mut rng);
                let b = unit4(&mut rng);
                let power = (rng.next_u32() % (2 * p)) as i32;
                let moved = lens.iso_apply(lens.deck(power), a);

                assert_relative_eq!(lens.distance(a, b), lens.distance(b, a), epsilon = 1e-5);
                assert_relative_eq!(lens.distance(moved, b), lens.distance(a, b), epsilon = 1e-4);
                assert!(lens.distance(a, moved) < 1e-3);
            }
        }
    }

    #[test]
    fn quotient_distance_never_exceeds_the_cover_distance_and_sometimes_beats_it() {
        let mut rng = Xorshift(0x7711_4402);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let mut beaten = 0;
            for _ in 0..5_000 {
                let a = unit4(&mut rng);
                let b = unit4(&mut rng);
                let quotient = lens.distance(a, b);
                let cover = SphericalS3Embedded.distance(a, b);
                assert!(
                    quotient <= cover + 1e-5,
                    "L({p}, {q}): quotient distance {quotient} exceeds the cover's {cover}"
                );
                if quotient < cover - 1e-3 {
                    beaten += 1;
                }
            }
            assert!(
                beaten > 100,
                "L({p}, {q}): the deck group shortened only {beaten} of 5000 pairs"
            );
        }
    }

    #[test]
    fn distance_satisfies_the_triangle_inequality() {
        let mut rng = Xorshift(0x7f4a_7c15);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            for _ in 0..5_000 {
                let a = unit4(&mut rng);
                let b = unit4(&mut rng);
                let c = unit4(&mut rng);
                assert!(lens.distance(a, c) <= lens.distance(a, b) + lens.distance(b, c) + 1e-4);
            }
        }
    }

    #[test]
    fn the_injectivity_radius_is_half_the_shortest_deck_displacement() {
        let mut rng = Xorshift(0x41c6_4e6d);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let mut shortest = f32::INFINITY;
            for _ in 0..20_000 {
                let x = unit4(&mut rng);
                for power in 1..p as i32 {
                    let moved = lens.iso_apply(lens.deck(power), x);
                    shortest = shortest.min(SphericalS3Embedded.distance(x, moved));
                }
            }
            assert_relative_eq!(shortest, TAU / p as f32, epsilon = 2e-3);
            assert_relative_eq!(lens.injectivity_radius(), 0.5 * shortest, epsilon = 1e-3);
        }
    }

    #[test]
    fn exp_and_log_invert_within_the_injectivity_radius() {
        let mut rng = Xorshift(0x6c07_8965);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let radius = lens.injectivity_radius();
            for _ in 0..5_000 {
                let at = unit4(&mut rng);
                let raw = unit4(&mut rng);
                let tangent = raw - raw.dot(at) * at;
                if tangent.length_squared() < 1e-6 {
                    continue;
                }
                let v = tangent.normalize() * (0.9 * radius);
                let recovered = lens.log(at, lens.exp(at, v));
                assert!(
                    (recovered - v).length() < 1e-4,
                    "L({p}, {q}): log(exp(v)) missed v by {}",
                    (recovered - v).length()
                );
            }

            // One full deck displacement along the `z1` plane is a closed
            // geodesic of the quotient: it returns to its own start, and the
            // short way home is the zero tangent, not the one travelled.
            let at = Vec4::X;
            let v = Vec4::Y * (TAU / p as f32);
            assert!(lens.distance(at, lens.exp(at, v)) < 1e-3);
            assert!(lens.log(at, lens.exp(at, v)).length() < 1e-3);
        }
    }

    #[test]
    fn log_length_equals_quotient_distance() {
        let mut rng = Xorshift(0x1c69_b3f5);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            for _ in 0..5_000 {
                let a = unit4(&mut rng);
                let b = unit4(&mut rng);
                assert_relative_eq!(lens.log(a, b).length(), lens.distance(a, b), epsilon = 1e-5);
            }
        }
    }

    #[test]
    fn parallel_transport_lands_tangent_to_the_lift_the_caller_named() {
        let mut rng = Xorshift(0x339a_cb15);
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            for _ in 0..5_000 {
                let from = unit4(&mut rng);
                let to = unit4(&mut rng);
                let raw = unit4(&mut rng);
                let v = raw - raw.dot(from) * from;
                let carried = lens.parallel_transport(from, to, v);
                assert!(
                    carried.dot(to).abs() < 1e-4,
                    "L({p}, {q}): transported vector is not tangent at `to`"
                );
                assert_relative_eq!(carried.length(), v.length(), epsilon = 1e-4);
            }
        }
    }

    #[test]
    fn the_wgsl_prelude_bakes_the_deck_table_the_rust_impl_computes() {
        for &(p, q) in LENSES {
            let lens = LensSpace::new(p, q);
            let source = lens.wgsl_prelude();
            for symbol in [
                "fn loam_lens_apply(",
                "fn loam_lens_wedge_offset(",
                "fn loam_lens_wrap(",
                "fn loam_lens_distance(",
                "fn loam_lens_nearest_power(",
                "const LOAM_LENS_P",
                "const LOAM_LENS_WEDGES_PER_TURN",
            ] {
                assert!(source.contains(symbol), "L({p}, {q}) is missing {symbol}");
            }

            let table = source
                .split("const LOAM_LENS_DECK = array<vec4<f32>, ")
                .nth(1)
                .and_then(|rest| rest.split(");").next())
                .expect("the deck table is baked");
            assert_eq!(
                table.matches("vec4<f32>(").count(),
                p as usize,
                "L({p}, {q}) baked {table}"
            );

            for (power, entry) in table.split("vec4<f32>(").skip(1).enumerate() {
                let baked: Vec<f32> = entry
                    .split(')')
                    .next()
                    .expect("a closed entry")
                    .split(", ")
                    .map(|coefficient| coefficient.parse().expect("an f32 literal"))
                    .collect();
                let m = lens.deck(power as i32).matrix;
                assert_eq!(
                    baked,
                    vec![m.x_axis.x, m.x_axis.y, m.z_axis.z, m.z_axis.w],
                    "L({p}, {q}): baked power {power} is not the Rust matrix"
                );
            }
        }
    }
}
